- project:
    name: theopenlab/spark
    check:
      jobs:
        - spark-build-and-test-arm64-core
        - spark-build-and-test-arm64-sql
        - spark-build-and-test-arm64-streaming-tools
        - spark-build-and-test-arm64-ml
        - spark-build-and-test-arm64-graphx-repl
        - spark-build-and-test-arm64-assembly-examples

- job:
    name: spark-build-and-test-arm64-core
    parent: init-test
    description: |
      The spark build in openlab cluster.
    run: .zuul/playbooks/spark-build/run-core.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400

- job:
    name: spark-build-and-test-arm64-sql
    parent: init-test
    description: |
      The spark build in openlab cluster.
    run: .zuul/playbooks/spark-build/run-sql.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400

- job:
    name: spark-build-and-test-arm64-streaming-tools
    parent: init-test
    description: |
      The spark build in openlab cluster.
    run: .zuul/playbooks/spark-build/run-streaming-tools.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400

- job:
    name: spark-build-and-test-arm64-ml
    parent: init-test
    description: |
      The spark build in openlab cluster.
    run: .zuul/playbooks/spark-build/run-ml.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400

- job:
    name: spark-build-and-test-arm64-graphx-repl
    parent: init-test
    description: |
      The spark build in openlab cluster.
    run: .zuul/playbooks/spark-build/run-graphx-repl.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400

- job:
    name: spark-build-and-test-arm64-assembly-examples
    parent: init-test
    description: |
      The spark build in openlab cluster.
    run: .zuul/playbooks/spark-build/run-assembly-examples.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400
