- project:
    name: theopenlab/spark
    check:
      jobs:
        - spark-build-and-test-arm64

- job:
    name: spark-build-and-test-arm64
    parent: init-test
    description: |
      The spark build and test sql module in openlab cluster.
    run: .zuul/playbooks/spark-build/run_all.yaml
    nodeset: ubuntu-xenial-arm64
    timeout: 86400
