- hosts: all
  become: yes
  tasks:
    - name: Build spark
      shell:
        cmd: |
          set -ex
          apt-get update -y

          # Install java
          apt-get install default-jre -y
          apt-get install default-jdk -y
          java_home=$(dirname $(dirname $(update-alternatives --list javac)))
          echo "export JAVA_HOME=${java_home}" >> ~/.profile
          echo "export PATH=${java_home}/bin:$PATH" >> ~/.profile
          source ~/.profile

          # Install maven
          wget http://www.us.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
          tar -xvf apache-maven-3.6.1-bin.tar.gz
          export PATH=$PWD/apache-maven-3.6.1/bin:$PATH
  
          # Install vim
          apt-get install vim -y
          
          # git snappy-1.0.5
          wget http://repository.timesys.com/buildsources/s/snappy/snappy-1.0.5/snappy-1.0.5.tar.gz
          tar -xvf snappy-1.0.5.tar.gz
          
          git clone http://github.com/huangtianhua/leveldbjni
          git clone http://github.com/huangtianhua/leveldb
          export SNAPPY_HOME=`cd snappy-1.0.5; pwd`
          export LEVELDBJNI_HOME=`cd leveldbjni; pwd`
          export LEVELDB_HOME=`cd leveldb; pwd`
          
          cd ${SNAPPY_HOME}
          # get the latest config.guess and config.sub
          wget -O config.guess "git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD"
          wget -O config.sub "git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD"
          ./configure --disable-shared --with-pic
          make
          
          cd ${LEVELDB_HOME}
          export LIBRARY_PATH=${SNAPPY_HOME}
          export C_INCLUDE_PATH=${LIBRARY_PATH}
          export CPLUS_INCLUDE_PATH=${LIBRARY_PATH}
          git apply ../leveldbjni/leveldb_aarch64.patch
          make libleveldb.a
          
          # fix the problem: 'aclocal-1.14' is missing on your system
          cd ../
          apt-get install autoconf -y
          wget http://ftp.gnu.org/gnu/automake/automake-1.14.tar.gz
          tar -zxvf automake-1.14.tar.gz
          cd automake-1.14
          ./bootstrap.sh
          ./configure
          make
          make install
  
          cd ${LEVELDBJNI_HOME}
          # fix error: configure.ac:36: error: required file 'autotools/compile' not found
          mkdir -p /usr/local/src/leveldbjni/leveldbjni-linux64-aarch64/target/native-build/autotools/
          cp /usr/local/share/automake-1.14/compile ${LEVELDBJNI_HOME}/leveldbjni-linux64-aarch64/target/native-build/autotools/
          # build leveldbjni-linux64-aarch64
          mvn install -P download -P linux64-aarch64
          # build leveldbjni-all
          mvn install -P download -P all
          
          # use local levedbjni jar built above
          export SPARK_HOME='/home/zuul/src/github.com/theopenlab/spark/'
          cp leveldbjni-all/target/leveldbjni-all-99-master-SNAPSHOT.jar ${SPARK_HOME}
          
          # build and test spark
          cd ${SPARK_HOME}
          ./build/mvn -DskipTests clean package
          
          # fix error: java.net.UnknownHostException: ubuntu: ubuntu: Name or service not known
          sed -i -e '/127.0.0.1/ s/\(localhost\)/'$(hostname)' \1/' /etc/hosts
          
          sleep 72000
          #./build/mvn test -fn
          
        chdir: '/usr/local/src'
        executable: /bin/bash
      environment: '{{ global_env }}'